feat(netlify): verification for edge middleware
withastro/adapters pull request #152
Opened 2024-02-05 17:01 UTC by lilnasy

## Changes
- Ensures that when `edgeMiddleware` is enabled, only the edge middleware can call the internal serverless function.

## Testing
Manual

## Docs
_Pending_

2024-02-05 17:01 UTC, lilnasy commented
!preview edge-middleware-verification

2024-02-05 17:05 UTC, Skn0tt requested changes
This is a risky change, and it's not obvious to me what attack vector this protects against. Could you outline that, either here or via email if you feel like it's too sensitive?

2024-02-05 17:07 UTC, lilnasy commented
This is motivated by the clerk vulnerability.

- [Investigating a major security vulnerability with Clerk's Next.js integration](https://pilcrow.vercel.app/blog/clerk-nextjs-vulnerability)
- [Clerk January 2024 Vulnerability Update](https://clerk.com/changelog/2024-02-02)

2024-02-05 17:18 UTC, Skn0tt commented
Got it, thanks! That looks like a spooky vuln definitely o.O

My understanding of the PR is that you want to ensure that the SSR function can only be reached via the Middleware, if there's a middleware configured. I don't think that attack vector exists currently, because the middleware is configured to run on all requests (except for the requests to Image CDN and static assets):

https://github.com/withastro/adapters/blob/7a5c3b06a7d62357dbeaa0fa060e35632aee61a4/packages/netlify/src/index.ts#L148

So there's no way of circumventing the Middleware function. We're already ensuring this works as expected inside of the CDN, I don't think we need another check in the adapter on top of that. Am I missing something here?

2024-02-05 23:03 UTC, lilnasy commented
Yeah, looks like Netlify gives us a guard rail, which is great. It would be even better to have a safety net on top of it.

2024-02-06 08:45 UTC, Skn0tt commented
Your call! If the behaviour is the same across all adapters, then it's fine I guess.

2024-02-06 12:41 UTC, lilnasy commented
@Skn0tt I have added you to a private thread in the #netlify channel of the astro discord. You might want to take that into account as well.

2024-02-06 13:37 UTC, Skn0tt approved these changes

2024-02-06 13:43 UTC, alexanderniebuhr reviewed
Pretty sure the changeset is good, but let's have docs take a look ;)

2024-02-06 13:45 UTC, sarah11918 approved these changes
Changeset looks great!!  :muscle:

2024-02-06 17:02 UTC, merged