Add imageService 'custom' to cloudflare integration
withastro/adapters pull request #229
Opened 2024-04-07 21:08 UTC by FlorianFlatscher

## Changes

- Added a new imageService option to cloudflare integraion: `custom`

## Testing

Not yet

## Docs

See (https://github.com/withastro/adapters/issues/228)
Closes (https://github.com/withastro/adapters/issues/228)

2024-04-08 05:17 UTC, alexanderniebuhr requested changes
@FlorianFlatscher Thanks for the contribution, this is actually something I wanted to add for months, but didn't have the time to do so. Very happy that you do it.

**This needs a Docs PR, once you created the PR in the docs repo, please cross-link them.** Your suggested docs are a good start, I would add some note that users need to make sure the custom image service is compatible with Cloudflare in production and that there are no guardlines or protections when using `imageService: 'custom'`

As for the code, that's a good start. Could you please also make sure the adapter options are updated? (https://github.com/withastro/adapters/blob/c22bb21f6bb0fece2bf29b9acaff08a78a6fce43/packages/cloudflare/src/index.ts#L20-L62)

It would also be great if you can add a changeset `pnpm exec changeset`, _(this would be a minor release)_.

Once those two things are addressed, I'm happy to do a final review and ship it.

2024-04-08 20:24 UTC, FlorianFlatscher commented
Thank you for your awesome guidance on my first contribution!

- I created and linked a docs pr
- Also updated adapter options
- changeset is in-coming

2024-04-08 20:49 UTC, alexanderniebuhr commented on .changeset/stupid-houses-laugh.md
> +Add imageService 'custom' to cloudflare integration
```suggestion
Adds a new option for the Image service to the Cloudflare adapter. `imageService: 'custom'` does use the user defined settings, without applying any modification to it. **You need to make sure that the configured settings are compatible with Cloudflare's `workerd` runtime yourself.**
```

2024-04-08 20:50 UTC, alexanderniebuhr approved these changes
Thanks for the contribution! ❤️

2024-04-09 04:45 UTC, alexanderniebuhr commented
Actually I need to try something to see if it is actually working, before I can merge this.

2024-04-10 08:13 UTC, merged