fix: remove vite.ssr.noExternal because it should use default.
withastro/adapters pull request #231
Opened 2024-04-09 11:15 UTC by mrthiti

## Changes

- Remove "vite.ssr.noExternal" because it should use default and it can append from astro config.

## Docs

Should remove this.
<img width="994" alt="image" src="https://github.com/withastro/adapters/assets/7018802/4f88a4d4-7002-4a49-a8ce-2cbeb628075f">

2024-04-09 12:11 UTC, alexanderniebuhr requested changes
@mrthiti Thank you for the thought. But I don't think this is correct. Can you explain why you think we should remove `vite.ssr.noExternal`? This setting is needed to be compatible with Cloudflare's workerd runtime.

2024-04-09 14:00 UTC, lilnasy commented
@mrthiti I'm not sure why qrcode would break because of this setting. It's hard to say whether this is the right solution without understanding the problem first.

Could you share a minimal project that breaks with the cloudflare adapter?

2024-04-10 04:35 UTC, mrthiti commented
Hi @lilnasy
This is mini project. Could you please "npm run build", it will error.
https://github.com/mrthiti/astro-cloudflare-root-cause

2024-04-10 05:16 UTC, alexanderniebuhr commented
@mrthiti Thank you for your reproduction, I'll create a new issue for it. The solution you proposed doesn't work for Cloudflare, because Cloudflare needs to have dependencies inlined on server build, which your solution disables.

2024-04-10 05:16 UTC, closed without merging