fix: cloudflare resolve conditions for svelte
withastro/adapters pull request #487
Opened 2024-12-16 11:32 UTC by rognstadragnar

## Changes

Fixes #485.

#476 added the `workerd` and `worker` resolve conditions to fix the Vue build breaking. As this fix used the `defaultClientConditions` as a base it broke builds using Svelte. The client default conditions include the `browser` condition, which makes Svelte use the client entry when server side rendering. 

I feel that the `defaultServerConditions` make the most sense as a default here, and with filtering out the `node` condition the Vue build will still work.

## Testing

Added usage of `setContext` to the Cloudflare Svelte fixture. 
Without this fix the tests then fail. With the fix all tests pass.

## Docs

Should not really affect anything as this is just a bug fix.

2024-12-18 10:24 UTC, ematipico approved these changes

2024-12-18 19:41 UTC, bluwy requested changes
I guess with #476, https://github.com/withastro/adapters/issues/410 resurfaced again and hasn't really been properly fixed. However, the behaviour now returns to the same as Vite 5 (and the previous major of the cloudflare adapter).

However, I don't know if this is the correct fix. We can't remove both "browser" and "node" conditions, either one needs to be enabled. I think I have to think a bit more about how to fix this first. There's an inconsistency where we're trying to use resolve conditions for Cloudflare (webworkers), but during dev, we're actually still running in node.

Blocking this for now but you can pin to the previous version that worked to workaround this at the meantime.

2024-12-19 12:55 UTC, alexanderniebuhr commented
@bluwy I feel like this is a good enough workaround for now. Are there any hard reasons not to merge this?

2024-12-25 18:10 UTC, bluwy commented
Closing this as fixed by https://github.com/sveltejs/svelte/pull/14779 (https://github.com/withastro/adapters/issues/485#issuecomment-2556402412)

2024-12-25 18:10 UTC, closed without merging